#! /usr/bin/perl

die "Usage: $0 <command>" unless @ARGV;

my $TIMES = 3;
my $SLEEP = 1;

my $SUCCESS = "./media/complete.oga";
my $ERROR = "./media/sonar.ogg";
my $PLAY = "/usr/bin/play";

# alerts (via noise) when done (with either error or success)
play(system(@ARGV) ? $ERROR : $SUCCESS);

sub play
{
	my $file = shift;

	close(STDERR);
	close(STDIN);

	foreach (1 .. $TIMES - 1)
	{
		system($PLAY, $file);
		sleep($SLEEP);
	}

	system($PLAY, $file); # don't sleep last time
}